export type Field={key:string;label:string;type?:string;options?:string[];required?:boolean};
export type ModuleConfig={title:string;table:string;description:string;fields:Field[];columns:string[];readOnly?:boolean};
const title:Field={key:'title',label:'Title',required:true};
const status:Field={key:'status',label:'Status',options:['Draft','Active','Completed','Archived']};
const description:Field={key:'description',label:'Description',type:'textarea'};
export const configs:Record<string,ModuleConfig>={
 team:{title:'Core team access',table:'users',description:'Grant or revoke module permissions for existing core team members.',fields:[{key:'permissions',label:'Module permissions JSON',type:'textarea'}],columns:['name','email','permissions']},
 applications:{title:'Applications',table:'applications',description:'Review candidates and move them through two interview rounds.',fields:[{key:'status',label:'Application stage',options:['Submitted','Under Review','Round 1 Shortlisted','Round 1 Rejected','Round 2 Shortlisted','Selected','Waitlisted','Rejected']},{key:'notes',label:'Review notes',type:'textarea'}],columns:['name','enrollment','email','status']},
 interviews:{title:'Interviews',table:'interviews',description:'Schedule rounds, assign panels, and record evaluations.',fields:[{key:'application_id',label:'Application ID',required:true},{key:'round',label:'Round',options:['1','2']},{key:'slot',label:'Interview time',type:'datetime-local',required:true},{key:'room',label:'Room',required:true},{key:'panel',label:'Panel emails (comma separated)'},{key:'score',label:'Score / 100',type:'number'},{key:'notes',label:'Evaluation notes',type:'textarea'},{key:'status',label:'Status',options:['Scheduled','Present','Absent','Completed']}],columns:['application_id','round','slot','room','score','status']},
 students:{title:'Students',table:'student_profiles',description:'Search students by name or unique enrollment number.',fields:[],columns:['name','enrollment','email','department','year'],readOnly:true},
 batches:{title:'Batches',table:'batches',description:'Create learning groups, assign mentors, and manage capacity.',fields:[title,{key:'code',label:'Batch code',required:true},{key:'capacity',label:'Capacity',type:'number',required:true},{key:'mentor',label:'Mentor'},{key:'faculty_mentor',label:'Faculty mentor'},{key:'room',label:'Room'},{key:'schedule',label:'Schedule'},{key:'start_date',label:'Start date',type:'date'},{key:'end_date',label:'End date',type:'date'},status,description],columns:['title','code','capacity','mentor','status']},
 syllabus:{title:'Syllabus',table:'syllabus',description:'Build tracks, modules, topics, sessions, and assignments for a batch.',fields:[title,{key:'batch_id',label:'Batch ID',required:true},{key:'track',label:'Track'},{key:'module_number',label:'Module number',type:'number'},{key:'topics',label:'Topics',type:'textarea'},{key:'session',label:'Session'},{key:'resource_url',label:'Resource URL',type:'url'},{key:'assignment',label:'Assignment',type:'textarea'},{key:'instructor',label:'Instructor'},{key:'expected_date',label:'Expected date',type:'date'},status],columns:['title','track','module_number','instructor','status']},
 circulars:{title:'Circulars',table:'circulars',description:'Share announcements with the right audience.',fields:[title,{key:'number',label:'Circular number',required:true},{key:'content',label:'Content',type:'textarea',required:true},{key:'audience',label:'Audience',options:['General','Batch','Faculty','Core Team']},{key:'batch_id',label:'Batch ID (required for Batch)'},{key:'priority',label:'Priority',options:['Normal','High','Urgent']},{key:'attachment_url',label:'Attachment URL',type:'url'},{key:'expires_at',label:'Expiry date',type:'date'},{key:'pinned',label:'Pinned',options:['false','true']}],columns:['title','number','audience','priority']},
 events:{title:'Events',table:'events',description:'Publish events, manage capacity, and open registration.',fields:[title,{key:'type',label:'Event type',options:['Workshop','Hackathon','AI Wars','Research','AI x Pharma','Industry Session','Guest Talk','Esports','Demo Day','Other']},description,{key:'starts_at',label:'Starts',type:'datetime-local',required:true},{key:'ends_at',label:'Ends',type:'datetime-local',required:true},{key:'venue',label:'Venue',required:true},{key:'capacity',label:'Participant capacity',type:'number',required:true},{key:'registration_opens',label:'Registration opens',type:'datetime-local',required:true},{key:'registration_closes',label:'Registration closes',type:'datetime-local',required:true},{key:'team',label:'Team event',options:['false','true']},{key:'team_size',label:'Team size',type:'number'},{key:'rules',label:'Rules',type:'textarea'},{key:'coordinator',label:'Coordinator'},{key:'contact',label:'Contact'},{key:'status',label:'Registration',options:['Open','Closed']},{key:'published',label:'Publish on website',options:['false','true']}],columns:['title','type','starts_at','capacity','status','published']},
 registrations:{title:'Registrations',table:'registrations',description:'Confirmed participants and waitlisted registrations.',fields:[],columns:['id','name','enrollment','event_id','status'],readOnly:true},
 attendance:{title:'Attendance',table:'attendance',description:'Record individual attendance for sessions and events.',fields:[{key:'student_id',label:'Student user ID',required:true},{key:'session',label:'Session / event title',required:true},{key:'date',label:'Date',type:'date',required:true},{key:'status',label:'Attendance',options:['Present','Absent']}],columns:['student_id','session','date','status']},
 research:{title:'Research pods',table:'research',description:'Follow research questions, experiments, and publication milestones.',fields:[title,{key:'area',label:'Research area'},{key:'problem',label:'Problem statement',type:'textarea'},{key:'faculty_mentor',label:'Faculty mentor'},{key:'external_mentor',label:'External mentor'},{key:'member_ids',label:'Member user IDs (comma separated)'},{key:'literature_status',label:'Literature review'},{key:'dataset',label:'Dataset'},{key:'model',label:'Model'},{key:'experiments',label:'Experiments',type:'textarea'},{key:'metrics',label:'Metrics'},{key:'paper_status',label:'Paper status'},{key:'publication',label:'Conference / journal'},{key:'milestones',label:'Milestones',type:'textarea'},status],columns:['title','area','faculty_mentor','paper_status','status']},
 industry:{title:'Industry projects',table:'industry',description:'Manage authorized partner projects and delivery milestones.',fields:[title,{key:'partner',label:'Company / partner'},{key:'problem',label:'Sanitized problem statement',type:'textarea'},{key:'confidential',label:'Confidential',options:['true','false']},{key:'owner',label:'Challenge owner'},{key:'member_ids',label:'Member user IDs (comma separated)'},{key:'stack',label:'Technology stack'},{key:'milestones',label:'Milestones',type:'textarea'},{key:'prototype_status',label:'Prototype status'},{key:'deployment_status',label:'Deployment status'},status],columns:['title','partner','owner','prototype_status','status']},
 esports:{title:'Esports',table:'esports',description:'Coordinate tournaments, teams, matches, and results.',fields:[title,{key:'game',label:'Game',options:['BGMI','Free Fire','Other']},{key:'team_name',label:'Team name'},{key:'players',label:'Player names and UIDs',type:'textarea'},{key:'group',label:'Group'},{key:'room',label:'Room'},{key:'match_time',label:'Match time',type:'datetime-local'},{key:'kill_points',label:'Kill points',type:'number'},{key:'placement_points',label:'Placement points',type:'number'},{key:'rank',label:'Final rank',type:'number'},status],columns:['title','game','team_name','kill_points','placement_points','rank']},
 certificates:{title:'Certificates',table:'certificates',description:'Share certificate links with individual students.',fields:[title,{key:'student_id',label:'Student user ID',required:true},{key:'url',label:'Certificate URL',type:'url',required:true}],columns:['title','student_id','url']},
 notifications:{title:'Notifications',table:'notifications',description:'Updates assigned to your account.',fields:[],columns:['title','message','created_at'],readOnly:true},
 users:{title:'Users & roles',table:'users',description:'Assign access by Google email. Privileged roles cannot be self-assigned.',fields:[{key:'name',label:'Full name',required:true},{key:'email',label:'Google email',type:'email',required:true},{key:'roles',label:'Roles (comma separated)',required:true},{key:'permissions',label:'Module permissions JSON',type:'textarea'},{key:'disabled',label:'Disabled',options:['false','true']}],columns:['name','email','roles','disabled']},
 configuration:{title:'Configuration',table:'configuration',description:'Maintain website settings and institutional master data.',fields:[{key:'title',label:'Configuration key',required:true},{key:'category',label:'Category',options:['Website','Institute','Department','Division','Academic year','Semester','Domain']},{key:'value',label:'Value',type:'textarea',required:true}],columns:['title','category','value']},
 audit:{title:'Activity log',table:'audit_logs',description:'An immutable record of administrative changes.',fields:[],columns:['created_at','actor_id','action','module','record_id'],readOnly:true}
};
