import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec('create role anon; create role authenticated; create role service_role;');
const migration=(await readFile('supabase/migrations/001_initial.sql','utf8')).replace('create extension if not exists pgcrypto;','');
await db.exec(migration);
console.log('PASS: Complete database migration executes.');
const insertUser=async(email,roles=['STUDENT'])=>(await db.query('insert into users(email,name,roles) values($1,$2,$3) returning id',[email,'Test user',roles])).rows[0].id;
await assert.rejects(()=>insertUser('student@gmail.com'));
console.log('PASS: Database rejects non-university student accounts.');
const admin=await insertUser('admin@example.com',['SUPER_ADMIN']);
const a=await insertUser('a@paruluniversity.ac.in');
const b=await insertUser('b@paruluniversity.ac.in');
const batch=(await db.query("select mutate_record('batches','create',null,$1,$2) as record",[JSON.stringify({title:'Test Batch',code:'T01',capacity:1}),admin])).rows[0].record;
await db.query('select assign_batch($1,$2,$3)',[batch.id,[a],admin]);
await assert.rejects(()=>db.query('select assign_batch($1,$2,$3)',[batch.id,[b],admin]),/capacity exceeded/);
console.log('PASS: Batch membership is atomic and capacity-limited.');
await db.query("select mutate_record('batches','edit',$1,$2,$3)",[batch.id,JSON.stringify({title:'Updated Batch'}),admin]);
assert.equal((await db.query('select title from batches where id=$1',[batch.id])).rows[0].title,'Updated Batch');
assert.equal((await db.query('select count(*)::int as n from audit_logs')).rows[0].n,3);
console.log('PASS: Administrative create/edit and batch assignment create audit entries.');
const event=(await db.query("insert into events(title,starts_at,ends_at,venue,capacity,registration_opens,registration_closes,status,published) values('Test Event',now()+interval '2 days',now()+interval '3 days','Lab',1,now()-interval '1 day',now()+interval '1 day','Open',true) returning id")).rows[0].id;
const participant=(name,email,enrollment)=>JSON.stringify({name,email,enrollment,phone:'9999999999',institute:'Engineering',department:'CSE',division:'A'});
const first=(await db.query('select * from register_for_event($1,$2,$3)',[event,a,participant('A','a@paruluniversity.ac.in','A01')])).rows[0];
const second=(await db.query('select * from register_for_event($1,$2,$3)',[event,b,participant('B','b@paruluniversity.ac.in','B01')])).rows[0];
assert.equal(first.status,'Confirmed');assert.equal(second.status,'Waitlisted');
await assert.rejects(()=>db.query('select register_for_event($1,$2,$3)',[event,a,participant('A','a@paruluniversity.ac.in','A01')]));
console.log('PASS: Event registrations respect capacity, waitlist overflow, and prevent duplicates.');
await db.exec('set role anon;');
await assert.rejects(()=>db.query('select * from users'));
await assert.rejects(()=>db.query("select mutate_record('users','delete',null,'{}',null)"));
await db.exec('reset role;');
console.log('PASS: Anonymous clients cannot read private records or execute privileged operations.');
await db.close();
