import {test,expect} from '@playwright/test';
import {can,type Member,portalRole} from '../src/lib/permissions';
const user=(roles:Member['roles'],permissions:Member['permissions']={}):Member=>({id:'test',email:'test@paruluniversity.ac.in',name:'Test',roles,permissions,disabled:false});
test('role boundaries prevent access escalation',()=>{
 const admin=user(['SUPER_ADMIN']);for(const module of ['users','configuration','audit','applications','attendance'])expect(can(admin,module,'delete')).toBe(true);
 const core=user(['CORE_TEAM']);expect(can(core,'tasks')).toBe(true);expect(can(core,'applications')).toBe(false);expect(can(core,'attendance','edit')).toBe(false);
 const granted=user(['CORE_TEAM'],{attendance:['view','edit'],applications:['view','edit','approve'],users:['view','edit']});expect(can(granted,'attendance','edit')).toBe(true);expect(can(granted,'applications','approve')).toBe(false);expect(can(granted,'users')).toBe(false);
 const faculty=user(['FACULTY']);expect(can(faculty,'progress')).toBe(true);expect(can(faculty,'attendance','edit')).toBe(false);expect(can(faculty,'feedback','create')).toBe(true);expect(can(faculty,'feedback','approve')).toBe(false);expect(can(user(['FACULTY'],{feedback:['approve']}),'feedback','approve')).toBe(true);
 const student=user(['STUDENT'],{users:['view'],attendance:['edit']});expect(can(student,'users')).toBe(false);expect(can(student,'attendance','edit')).toBe(false);expect(can(student,'progress','edit')).toBe(true);expect(portalRole(user(['STUDENT','SUPER_ADMIN']))).toBe('admin');
 expect(can({...admin,disabled:true},'users')).toBe(false);
});
for(const [role,title] of [['admin','RUN THE CLUB.'],['core-team','MAKE IT HAPPEN.'],['faculty','GUIDE WHAT’S NEXT.'],['student','YOUR NEXT CHAPTER.']]){
 test(`${role} has a distinct responsive dashboard`,async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto(`/preview?role=${role}`);await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(['admin','core-team'].includes(role)){await expect(page.getByRole('region',{name:'Interview and club updates'})).toHaveCount(0)}if(role==='student'){await expect(page.getByRole('navigation',{name:'Portal navigation'}).getByText('Users & roles')).toHaveCount(0)}await page.screenshot({path:`artifacts/portal-${role}-mobile.png`,fullPage:true})});
}
test('access editor uses roles and checkboxes, not raw IDs or JSON',async({page})=>{await page.goto('/preview?role=admin&module=users');await expect(page.getByRole('heading',{name:'Assign roles by email'})).toBeVisible();await expect(page.getByLabel('Google email',{exact:true})).toBeVisible();await page.getByRole('checkbox',{name:'Core Team',exact:true}).check();await expect(page.getByText('Module permissions',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Save roles & permissions'})).toBeDisabled();await page.setViewportSize({width:320,height:800});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)});
test('new operations require authentication and same-origin writes',async({request})=>{expect((await request.get('/api/operations?view=users')).status()).toBe(401);expect((await request.post('/api/operations',{headers:{Origin:'http://localhost:3000'},data:{action:'finalize',data:{}}})).status()).toBe(401);expect((await request.post('/api/operations',{headers:{Origin:'https://attacker.invalid'},data:{}})).status()).toBe(403)});
