import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowUpRight} from 'lucide-react';
import {PageShell} from '@/components/page-shell';
const content:Record<string,{title:string;description:string;items:[string,string][]}>={
 learning:{title:'START CURIOUS.\nBUILD CONFIDENT.',description:'A learning roadmap designed to turn curiosity into capability. Start at the fundamentals, then put every new skill to work.',items:[['Python for AI','Variables, functions, data structures, and the tools you’ll use every day.'],['NumPy & Pandas','Work with arrays, clean real datasets, and find the story in the data.'],['Visualize & Explore','Discover patterns and communicate your findings with clear visualizations.'],['Machine Learning','Understand regression, classification, training, and model evaluation.'],['Measure What Matters','Precision, recall, F1 scores, and building models you can trust.'],['Your First AI Project','Bring it all together. Build, present, and share a working AI project.']]},
 research:{title:'BIG QUESTIONS.\nNEW POSSIBILITIES.',description:'Research is a team sport. Work with fellow students and faculty mentors to explore ideas, design experiments, and contribute something new.',items:[['Find your research pod','Connect around a shared question in computer vision, NLP, responsible AI, or applied machine learning.'],['Explore the literature','Understand what’s already out there, identify a gap, and define your problem.'],['Experiment together','Work with datasets, compare models, and record results through shared milestones.'],['Share what you discover','Develop your findings into a paper, poster, or conference submission with mentor guidance.']]},
 industry:{title:'BEYOND THE\nCLASSROOM.',description:'Apply what you know to problems that matter. Collaborate on practical industry challenges, build prototypes, and learn how real teams deliver.',items:[['Discover a challenge','Explore sanitized problem statements shared by club partners.'],['Build your team','Bring together complementary skills across AI, development, design, and communication.'],['Prototype & iterate','Work through milestones, test your approach, and learn from mentor feedback.'],['Make an impact','Demonstrate your solution and document the thinking behind it.']]},
 esports:{title:'YOUR SQUAD.\nYOUR STAGE.',description:'Strategy, teamwork, and a little competitive spirit. Find your people through campus tournaments and the Nexus gaming community.',items:[['BGMI','Squad-based competitions with structured matches and shared leaderboards.'],['Free Fire','Bring your team and compete in club-organized tournaments.'],['Play fair','Respect your opponents, follow tournament rules, and keep the competition welcoming.'],['Find your next match','Published tournaments include schedules, registration, and room information for participants.']]},
 team:{title:'BUILT BY STUDENTS.\nPOWERED BY PEOPLE.',description:'A community of learners, builders, researchers, and mentors at Parul University.',items:[['Club leads','Shape the community, coordinate opportunities, and support every domain.'],['Core team','The people making events, learning, design, media, and community happen.'],['Faculty mentors','Academic guidance and support for learning and research.'],['You belong here','Apply to become part of the next chapter of AI Nexus.']]}
};
export default async function Explore({params}:{params:Promise<{domain:string}>}){const{domain}=await params;const data=content[domain];if(!data)notFound();return <PageShell><span className="eyebrow">AI NEXUS / {domain.toUpperCase()}</span><h1 className="page-title" style={{whiteSpace:'pre-line'}}>{data.title}</h1><p className="page-description">{data.description}</p><div className="module-list">{data.items.map(([title,text],i)=><div className="module-item" key={title}><span>0{i+1} / {domain.toUpperCase()}</span><h3>{title}</h3><p>{text}</p></div>)}</div><div style={{marginTop:35}}><Link className="primary-button" href={domain==='esports'?'/events':'/apply'}>{domain==='esports'?'Explore events':'Find your place'}<ArrowUpRight size={18}/></Link></div></PageShell>}
