import Link from 'next/link';
import {ArrowUpRight, ArrowRight, Sparkles, Code2, Globe2, Plus} from 'lucide-react';
import {Header} from '@/components/header';
import {Brand,Doodle,Orb} from '@/components/brand';
import {events,tracks} from '@/lib/content';
export default function Home(){return <main className="site-shell">
 <section className="blue-stage"><Header/><div className="hero"><div className="hero-grid"/><span className="hero-hash" aria-hidden="true">#</span><div className="hero-kicker"><span/> PARUL UNIVERSITY’S AI COMMUNITY</div><h1><span>AI NEXUS</span><span>BUILD THE</span><span>FUTURE.</span></h1><Doodle className="arrow-top"/><Doodle className="arrow-bottom"/>
 <Link href="/events/ai-wars" className="float-card float-one"><Orb kind="atom"/><strong>AI Wars</strong><small>Big ideas. Real impact.</small><span className="mini-pill">LET’S BUILD ↗</span></Link>
 <Link href="/#research" className="float-card float-two"><Orb kind="code"/><strong>Research pods</strong><small>Curiosity, connected.</small></Link>
 <Link href="/apply" className="round-cta" aria-label="Get started, join AI Nexus"><svg viewBox="0 0 160 160" aria-hidden="true"><defs><path id="circle-text" d="M80 80m-62 0a62 62 0 1 1 124 0a62 62 0 1 1-124 0"/></defs><text><textPath href="#circle-text" textLength="385">GET STARTED • BUILD YOUR FUTURE • </textPath></text></svg><Doodle/></Link>
 <div className="hero-bottom"><p>A student AI ecosystem.<br/>Limitless ideas. One community.</p><Link href="#events">Find your next big thing <ArrowRight size={16}/></Link><span className="hero-index">SCROLL TO EXPLORE ↓</span></div></div></section>
 <section className="white-stage" id="learning"><div className="feature-row"><Link href="/explore/learning" className="feature"><span className="feature-no">01 / LEARN</span><h2>SMALL STEPS.<br/>BIG POSSIBILITIES.</h2><p>Your AI journey starts right here.</p><div className="feature-bottom"><span className="mini-blue"><Code2 size={20}/> AI FUNDAMENTALS</span><b className="lime-pill">START LEARNING ↗</b></div></Link><Link href="/explore/industry" className="feature"><span className="feature-no">02 / BUILD</span><h2>REAL IDEAS.<br/>REAL-WORLD IMPACT.</h2><p>Go from “what if” to “I built this.”</p><div className="feature-bottom blue-pill"><span>LEARN IT. BUILD IT.</span><ArrowUpRight size={23}/></div></Link><Link href="/explore/research" className="feature"><span className="feature-no">03 / GO BEYOND</span><h2>STAY CURIOUS.<br/>MAKE YOUR MARK.</h2><p>Research, compete, and find your people.</p><div className="feature-bottom"><b className="big-lime">EXPLORE TOGETHER <Sparkles size={21}/></b></div></Link><Doodle className="feature-doodle"/></div>
 <div className="intro-section" id="about"><div><span className="eyebrow"><span/> NOT JUST ANOTHER CLUB</span><h2>YOUR PEOPLE.<br/>YOUR <em>POSSIBILITIES.</em></h2></div><div className="intro-copy"><p>For the curious minds. The late-night builders. The “what if we tried this?” people.</p><p>AI Nexus brings students at Parul University together to learn artificial intelligence, build meaningful projects, and explore what comes next. Wherever you’re starting, there’s a place for you here.</p><Link href="/apply" className="text-link">Find your place <ArrowUpRight size={18}/></Link></div></div>
 <div className="section-heading" id="events"><div><span className="eyebrow"><span/> MEET. MAKE. MAKE SOME NOISE.</span><h2>NEXT UP AT NEXUS<span className="lime-dot">.</span></h2></div><Link href="/events" className="outline-button">Explore events <ArrowUpRight size={16}/></Link></div>
 <p className="preview-note">A look at what’s possible · Illustrative events until the club publishes its calendar</p><div className="events-grid">{events.map((event,i)=><Link key={event.id} href={`/events/${event.id}`} className="event-card"><div className={`event-art ${event.art}`}><div className="event-art-top"><span>AI NEXUS / {event.type.toUpperCase()}</span><ArrowUpRight size={19}/></div><span className="event-art-label">{event.label}</span><h3>{event.title}</h3><div className="event-symbol" aria-hidden="true">{i===0?'✳':i===1?'{ }':'↗'}</div><span className="art-bottom">THE FUTURE IS A TEAM SPORT.</span></div><div className="event-meta"><span className="event-category">{event.type}</span><span>{event.date} <ArrowUpRight size={14}/></span></div><h3>{event.title.replace('\n',' ')}</h3><p>{event.description}</p></Link>)}</div>
 <section className="possibility-section" id="research"><div className="section-heading"><div><span className="eyebrow"><span/> ONE COMMUNITY. MANY DIRECTIONS.</span><h2>FOLLOW YOUR CURIOSITY.</h2></div><Globe2 size={44}/></div><div className="track-grid">{tracks.map((track,i)=><Link href={`/explore/${['learning','research','industry','esports'][i]}`} className="track" key={track.title}><span className="track-number">0{i+1}</span><div><span className="eyebrow">{track.tag}</span><h3>{track.title}</h3><p>{track.text}</p></div><ArrowUpRight/></Link>)}</div></section>
 <section className="community-section" id="community"><span className="eyebrow">GOOD THINGS START WITH A HELLO.</span><h2>THE NEXT BIG THING<br/>STARTS WITH <span>YOU.</span></h2><p>You don’t need to know it all. Just bring your curiosity.</p><Link href="/apply" className="lime-button">Join AI Nexus <ArrowUpRight size={20}/></Link><Doodle/></section>
 <section className="faq-section"><div><span className="eyebrow"><span/> A LITTLE MORE CLARITY</span><h2>CURIOUS?<br/>GOOD.</h2></div><div>{[['Do I need to know AI to join?','No. Curiosity is the only prerequisite. Our learning tracks start with the fundamentals and grow with you.'],['Who can become a member?','Students at Parul University can apply. Student sign-in requires a verified @paruluniversity.ac.in Google account.'],['How does the selection process work?','Submit your application, then follow your status through review and two interview rounds. The club team will share your interview details.'],['Can I join more than one domain?','Absolutely. Explore learning, research, industry projects, and esports. Your interests can evolve as you do.']].map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section>
 <footer><div className="footer-top"><Brand/><span>Build the future. Together.</span><Link href="/login">Member login <ArrowUpRight size={16}/></Link></div><div className="footer-bottom"><span>© {new Date().getFullYear()} AI Nexus · Parul University</span><div><Link href="/explore/team">The team</Link><Link href="/privacy">Privacy</Link><Link href="/apply">Get in touch ↗</Link></div><span>MADE FOR WHAT’S NEXT ✳</span></div></footer>
 </section></main>}
